SPRING_APPLICATION_NAME=ms-account-reservation
SERVER_PORT=8080

DB_HOST=localhost
DB_PORT=5432
DB_NAME=account_reservation
DB_USERNAME=postgres
DB_PASSWORD=postgres

JPA_HIBERNATE_DDL_AUTO=none
JPA_SHOW_SQL=false
HIBERNATE_FORMAT_SQL=true

LOGGING_LEVEL_ROOT=INFO
LOGGING_LEVEL_APP=INFO
