spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: ${LIQUIBASE_ENABLED}
    change-log: ${LIQUIBASE_CHANGE_LOG}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL}

server:
  port: ${SERVER_PORT}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}
    org.example: ${LOGGING_LEVEL_APP}
